### ISSUE TITLE
findDOMNode was called on an unmounted component

### ISSUE THREAD

**Issue by manumaticx** [patrickgalbraith/react-equalizer#4] opened 2017-01-11 12:27 UTC
I randomly get this error. I'll investigate and let you know when I find out how to reproduce it.
```
invariant.js:38 Uncaught Error: findDOMNode was called on an unmounted component.
    at invariant (invariant.js:38)
    at Object.findDOMNode (findDOMNode.js:54)
    at Equalizer.updateChildrenHeights (equalizer.js:73)
```

**Comment by patrickgalbraith** [comment] 2017-01-24 09:48
Did you manage to find anything? This shouldn't happen since the resize event is removed when the component is unmounted.

**Comment by theisof** [comment] 2017-02-01 21:31
I get the exact same error. Happens when I navigate away from a view with Equalizer. Yet, it's only when Equalizer is part of the initial render - not when I navigate to and away from this view (I'm using react-router).

**Comment by patrickgalbraith** [comment] 2017-02-02 00:27
@manumaticx @theisof Try 1.0.6 I have cancelled the debounce when the node in unmounted. Hopefully that should fix the problem you are having.

**Comment by patrickgalbraith** [comment] 2017-02-02 11:41
I have also added a check to 1.1.0 after changing the way the node is referenced.

**Comment by billymoon** [comment] 2017-02-14 14:02
@manumaticx @theisof are you guys able to reproduce this issue in 1.0.6+ ... is this still an issue..?

**Comment by theisof** [comment] 2017-03-30 20:54
Sorry for the late reply (I need to adjust my Github notification settings). I upgraded to 1.2.0 and no longer have the error. Thanks :-) 

I think you can close this issue.

**Closed as completed** 2017-05-26 11:26 UTC
